#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

use Net::Rajce;
use Net::Netrc;

my $rajce = new Rajce;

my $mach = Net::Netrc->lookup($rajce->{API});
my ($mail, $password, $account) = $mach->lpa;

my $login = $rajce->login($mail,$password);

print Dumper($rajce->list());
