#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Std;
use Net::Netrc;
use Net::Rajce;

my %opts;
getopt('t:', \%opts);  

if(!@ARGV or !$opts{t}){
	print "Usage: rajce-put -t 'Title' file.jpg file2.jpg ...\n";
	exit;
}

my $rajce = new Rajce;

my $mach = Net::Netrc->lookup($rajce->{API});
my ($mail, $password, $account) = $mach->lpa;

my $login = $rajce->login($mail,$password);

my $album = $rajce->create_album($opts{t},'');

foreach my $file(@ARGV){
	$rajce->add_photo($file,$album)
}
